(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.bytes.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.cryptoffi.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.cryptoutil.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.safemarshal.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.golang.theory.

Require Export New.code.github_com.sanjit_bhat.pav.ktcore.

Set Default Proof Using "Type".

Module ktcore.

(* type ktcore.Blame *)
Module Blame.

#[global] Transparent ktcore.Blame.
#[global] Typeclasses Transparent ktcore.Blame.
Section def.
Context `{ffi_syntax}.
Definition t := w64.
End def.
End Blame.

(* type ktcore.Evid *)
Module Evid.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Vrf' : loc;
  Link' : loc;
}.
End def.
End Evid.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.Evid.
#[local] Typeclasses Transparent ktcore.Evid.

Global Instance Evid_wf : struct.Wf ktcore.Evid.
Proof. apply _. Qed.

Global Instance settable_Evid : Settable Evid.t :=
  settable! Evid.mk < Evid.Vrf'; Evid.Link' >.
Global Instance into_val_Evid : IntoVal Evid.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.Evid [
    "Vrf" ::= #(Evid.Vrf' v);
    "Link" ::= #(Evid.Link' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_Evid : IntoValTyped Evid.t ktcore.Evid :=
{|
  default_val := Evid.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_Evid_Vrf : IntoValStructField "Vrf" ktcore.Evid Evid.Vrf'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_Evid_Link : IntoValStructField "Link" ktcore.Evid Evid.Link'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_Evid Vrf' Link':
  PureWp True
    (struct.make #ktcore.Evid (alist_val [
      "Vrf" ::= #Vrf';
      "Link" ::= #Link'
    ]))%struct
    #(Evid.mk Vrf' Link').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance Evid_struct_fields_split dq l (v : Evid.t) :
  StructFieldsSplit dq l v (
    "HVrf" ∷ l ↦s[ktcore.Evid :: "Vrf"]{dq} v.(Evid.Vrf') ∗
    "HLink" ∷ l ↦s[ktcore.Evid :: "Link"]{dq} v.(Evid.Link')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (Evid.Vrf' v)) (ktcore.Evid) "Vrf"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.EvidVrf *)
Module EvidVrf.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  VrfPk0' : slice.t;
  Sig0' : slice.t;
  VrfPk1' : slice.t;
  Sig1' : slice.t;
}.
End def.
End EvidVrf.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.EvidVrf.
#[local] Typeclasses Transparent ktcore.EvidVrf.

Global Instance EvidVrf_wf : struct.Wf ktcore.EvidVrf.
Proof. apply _. Qed.

Global Instance settable_EvidVrf : Settable EvidVrf.t :=
  settable! EvidVrf.mk < EvidVrf.VrfPk0'; EvidVrf.Sig0'; EvidVrf.VrfPk1'; EvidVrf.Sig1' >.
Global Instance into_val_EvidVrf : IntoVal EvidVrf.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.EvidVrf [
    "VrfPk0" ::= #(EvidVrf.VrfPk0' v);
    "Sig0" ::= #(EvidVrf.Sig0' v);
    "VrfPk1" ::= #(EvidVrf.VrfPk1' v);
    "Sig1" ::= #(EvidVrf.Sig1' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_EvidVrf : IntoValTyped EvidVrf.t ktcore.EvidVrf :=
{|
  default_val := EvidVrf.mk (default_val _) (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_EvidVrf_VrfPk0 : IntoValStructField "VrfPk0" ktcore.EvidVrf EvidVrf.VrfPk0'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidVrf_Sig0 : IntoValStructField "Sig0" ktcore.EvidVrf EvidVrf.Sig0'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidVrf_VrfPk1 : IntoValStructField "VrfPk1" ktcore.EvidVrf EvidVrf.VrfPk1'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidVrf_Sig1 : IntoValStructField "Sig1" ktcore.EvidVrf EvidVrf.Sig1'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_EvidVrf VrfPk0' Sig0' VrfPk1' Sig1':
  PureWp True
    (struct.make #ktcore.EvidVrf (alist_val [
      "VrfPk0" ::= #VrfPk0';
      "Sig0" ::= #Sig0';
      "VrfPk1" ::= #VrfPk1';
      "Sig1" ::= #Sig1'
    ]))%struct
    #(EvidVrf.mk VrfPk0' Sig0' VrfPk1' Sig1').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance EvidVrf_struct_fields_split dq l (v : EvidVrf.t) :
  StructFieldsSplit dq l v (
    "HVrfPk0" ∷ l ↦s[ktcore.EvidVrf :: "VrfPk0"]{dq} v.(EvidVrf.VrfPk0') ∗
    "HSig0" ∷ l ↦s[ktcore.EvidVrf :: "Sig0"]{dq} v.(EvidVrf.Sig0') ∗
    "HVrfPk1" ∷ l ↦s[ktcore.EvidVrf :: "VrfPk1"]{dq} v.(EvidVrf.VrfPk1') ∗
    "HSig1" ∷ l ↦s[ktcore.EvidVrf :: "Sig1"]{dq} v.(EvidVrf.Sig1')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (EvidVrf.VrfPk0' v)) (ktcore.EvidVrf) "VrfPk0"%go.
  simpl_one_flatten_struct (# (EvidVrf.Sig0' v)) (ktcore.EvidVrf) "Sig0"%go.
  simpl_one_flatten_struct (# (EvidVrf.VrfPk1' v)) (ktcore.EvidVrf) "VrfPk1"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.EvidLink *)
Module EvidLink.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Epoch' : w64;
  Link0' : slice.t;
  Sig0' : slice.t;
  Link1' : slice.t;
  Sig1' : slice.t;
}.
End def.
End EvidLink.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.EvidLink.
#[local] Typeclasses Transparent ktcore.EvidLink.

Global Instance EvidLink_wf : struct.Wf ktcore.EvidLink.
Proof. apply _. Qed.

Global Instance settable_EvidLink : Settable EvidLink.t :=
  settable! EvidLink.mk < EvidLink.Epoch'; EvidLink.Link0'; EvidLink.Sig0'; EvidLink.Link1'; EvidLink.Sig1' >.
Global Instance into_val_EvidLink : IntoVal EvidLink.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.EvidLink [
    "Epoch" ::= #(EvidLink.Epoch' v);
    "Link0" ::= #(EvidLink.Link0' v);
    "Sig0" ::= #(EvidLink.Sig0' v);
    "Link1" ::= #(EvidLink.Link1' v);
    "Sig1" ::= #(EvidLink.Sig1' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_EvidLink : IntoValTyped EvidLink.t ktcore.EvidLink :=
{|
  default_val := EvidLink.mk (default_val _) (default_val _) (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_EvidLink_Epoch : IntoValStructField "Epoch" ktcore.EvidLink EvidLink.Epoch'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidLink_Link0 : IntoValStructField "Link0" ktcore.EvidLink EvidLink.Link0'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidLink_Sig0 : IntoValStructField "Sig0" ktcore.EvidLink EvidLink.Sig0'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidLink_Link1 : IntoValStructField "Link1" ktcore.EvidLink EvidLink.Link1'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_EvidLink_Sig1 : IntoValStructField "Sig1" ktcore.EvidLink EvidLink.Sig1'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_EvidLink Epoch' Link0' Sig0' Link1' Sig1':
  PureWp True
    (struct.make #ktcore.EvidLink (alist_val [
      "Epoch" ::= #Epoch';
      "Link0" ::= #Link0';
      "Sig0" ::= #Sig0';
      "Link1" ::= #Link1';
      "Sig1" ::= #Sig1'
    ]))%struct
    #(EvidLink.mk Epoch' Link0' Sig0' Link1' Sig1').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance EvidLink_struct_fields_split dq l (v : EvidLink.t) :
  StructFieldsSplit dq l v (
    "HEpoch" ∷ l ↦s[ktcore.EvidLink :: "Epoch"]{dq} v.(EvidLink.Epoch') ∗
    "HLink0" ∷ l ↦s[ktcore.EvidLink :: "Link0"]{dq} v.(EvidLink.Link0') ∗
    "HSig0" ∷ l ↦s[ktcore.EvidLink :: "Sig0"]{dq} v.(EvidLink.Sig0') ∗
    "HLink1" ∷ l ↦s[ktcore.EvidLink :: "Link1"]{dq} v.(EvidLink.Link1') ∗
    "HSig1" ∷ l ↦s[ktcore.EvidLink :: "Sig1"]{dq} v.(EvidLink.Sig1')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (EvidLink.Epoch' v)) (ktcore.EvidLink) "Epoch"%go.
  simpl_one_flatten_struct (# (EvidLink.Link0' v)) (ktcore.EvidLink) "Link0"%go.
  simpl_one_flatten_struct (# (EvidLink.Sig0' v)) (ktcore.EvidLink) "Sig0"%go.
  simpl_one_flatten_struct (# (EvidLink.Link1' v)) (ktcore.EvidLink) "Link1"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.VrfSig *)
Module VrfSig.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  SigTag' : w8;
  VrfPk' : slice.t;
}.
End def.
End VrfSig.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.VrfSig.
#[local] Typeclasses Transparent ktcore.VrfSig.

Global Instance VrfSig_wf : struct.Wf ktcore.VrfSig.
Proof. apply _. Qed.

Global Instance settable_VrfSig : Settable VrfSig.t :=
  settable! VrfSig.mk < VrfSig.SigTag'; VrfSig.VrfPk' >.
Global Instance into_val_VrfSig : IntoVal VrfSig.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.VrfSig [
    "SigTag" ::= #(VrfSig.SigTag' v);
    "VrfPk" ::= #(VrfSig.VrfPk' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_VrfSig : IntoValTyped VrfSig.t ktcore.VrfSig :=
{|
  default_val := VrfSig.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_VrfSig_SigTag : IntoValStructField "SigTag" ktcore.VrfSig VrfSig.SigTag'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_VrfSig_VrfPk : IntoValStructField "VrfPk" ktcore.VrfSig VrfSig.VrfPk'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_VrfSig SigTag' VrfPk':
  PureWp True
    (struct.make #ktcore.VrfSig (alist_val [
      "SigTag" ::= #SigTag';
      "VrfPk" ::= #VrfPk'
    ]))%struct
    #(VrfSig.mk SigTag' VrfPk').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance VrfSig_struct_fields_split dq l (v : VrfSig.t) :
  StructFieldsSplit dq l v (
    "HSigTag" ∷ l ↦s[ktcore.VrfSig :: "SigTag"]{dq} v.(VrfSig.SigTag') ∗
    "HVrfPk" ∷ l ↦s[ktcore.VrfSig :: "VrfPk"]{dq} v.(VrfSig.VrfPk')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (VrfSig.SigTag' v)) (ktcore.VrfSig) "SigTag"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.LinkSig *)
Module LinkSig.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  SigTag' : w8;
  Epoch' : w64;
  Link' : slice.t;
}.
End def.
End LinkSig.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.LinkSig.
#[local] Typeclasses Transparent ktcore.LinkSig.

Global Instance LinkSig_wf : struct.Wf ktcore.LinkSig.
Proof. apply _. Qed.

Global Instance settable_LinkSig : Settable LinkSig.t :=
  settable! LinkSig.mk < LinkSig.SigTag'; LinkSig.Epoch'; LinkSig.Link' >.
Global Instance into_val_LinkSig : IntoVal LinkSig.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.LinkSig [
    "SigTag" ::= #(LinkSig.SigTag' v);
    "Epoch" ::= #(LinkSig.Epoch' v);
    "Link" ::= #(LinkSig.Link' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_LinkSig : IntoValTyped LinkSig.t ktcore.LinkSig :=
{|
  default_val := LinkSig.mk (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_LinkSig_SigTag : IntoValStructField "SigTag" ktcore.LinkSig LinkSig.SigTag'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_LinkSig_Epoch : IntoValStructField "Epoch" ktcore.LinkSig LinkSig.Epoch'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_LinkSig_Link : IntoValStructField "Link" ktcore.LinkSig LinkSig.Link'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_LinkSig SigTag' Epoch' Link':
  PureWp True
    (struct.make #ktcore.LinkSig (alist_val [
      "SigTag" ::= #SigTag';
      "Epoch" ::= #Epoch';
      "Link" ::= #Link'
    ]))%struct
    #(LinkSig.mk SigTag' Epoch' Link').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance LinkSig_struct_fields_split dq l (v : LinkSig.t) :
  StructFieldsSplit dq l v (
    "HSigTag" ∷ l ↦s[ktcore.LinkSig :: "SigTag"]{dq} v.(LinkSig.SigTag') ∗
    "HEpoch" ∷ l ↦s[ktcore.LinkSig :: "Epoch"]{dq} v.(LinkSig.Epoch') ∗
    "HLink" ∷ l ↦s[ktcore.LinkSig :: "Link"]{dq} v.(LinkSig.Link')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (LinkSig.SigTag' v)) (ktcore.LinkSig) "SigTag"%go.
  simpl_one_flatten_struct (# (LinkSig.Epoch' v)) (ktcore.LinkSig) "Epoch"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.MapLabel *)
Module MapLabel.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Uid' : w64;
  Ver' : w64;
}.
End def.
End MapLabel.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.MapLabel.
#[local] Typeclasses Transparent ktcore.MapLabel.

Global Instance MapLabel_wf : struct.Wf ktcore.MapLabel.
Proof. apply _. Qed.

Global Instance settable_MapLabel : Settable MapLabel.t :=
  settable! MapLabel.mk < MapLabel.Uid'; MapLabel.Ver' >.
Global Instance into_val_MapLabel : IntoVal MapLabel.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.MapLabel [
    "Uid" ::= #(MapLabel.Uid' v);
    "Ver" ::= #(MapLabel.Ver' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_MapLabel : IntoValTyped MapLabel.t ktcore.MapLabel :=
{|
  default_val := MapLabel.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_MapLabel_Uid : IntoValStructField "Uid" ktcore.MapLabel MapLabel.Uid'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_MapLabel_Ver : IntoValStructField "Ver" ktcore.MapLabel MapLabel.Ver'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_MapLabel Uid' Ver':
  PureWp True
    (struct.make #ktcore.MapLabel (alist_val [
      "Uid" ::= #Uid';
      "Ver" ::= #Ver'
    ]))%struct
    #(MapLabel.mk Uid' Ver').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance MapLabel_struct_fields_split dq l (v : MapLabel.t) :
  StructFieldsSplit dq l v (
    "HUid" ∷ l ↦s[ktcore.MapLabel :: "Uid"]{dq} v.(MapLabel.Uid') ∗
    "HVer" ∷ l ↦s[ktcore.MapLabel :: "Ver"]{dq} v.(MapLabel.Ver')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (MapLabel.Uid' v)) (ktcore.MapLabel) "Uid"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.CommitOpen *)
Module CommitOpen.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Val' : slice.t;
  Rand' : slice.t;
}.
End def.
End CommitOpen.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.CommitOpen.
#[local] Typeclasses Transparent ktcore.CommitOpen.

Global Instance CommitOpen_wf : struct.Wf ktcore.CommitOpen.
Proof. apply _. Qed.

Global Instance settable_CommitOpen : Settable CommitOpen.t :=
  settable! CommitOpen.mk < CommitOpen.Val'; CommitOpen.Rand' >.
Global Instance into_val_CommitOpen : IntoVal CommitOpen.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.CommitOpen [
    "Val" ::= #(CommitOpen.Val' v);
    "Rand" ::= #(CommitOpen.Rand' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_CommitOpen : IntoValTyped CommitOpen.t ktcore.CommitOpen :=
{|
  default_val := CommitOpen.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_CommitOpen_Val : IntoValStructField "Val" ktcore.CommitOpen CommitOpen.Val'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_CommitOpen_Rand : IntoValStructField "Rand" ktcore.CommitOpen CommitOpen.Rand'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_CommitOpen Val' Rand':
  PureWp True
    (struct.make #ktcore.CommitOpen (alist_val [
      "Val" ::= #Val';
      "Rand" ::= #Rand'
    ]))%struct
    #(CommitOpen.mk Val' Rand').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance CommitOpen_struct_fields_split dq l (v : CommitOpen.t) :
  StructFieldsSplit dq l v (
    "HVal" ∷ l ↦s[ktcore.CommitOpen :: "Val"]{dq} v.(CommitOpen.Val') ∗
    "HRand" ∷ l ↦s[ktcore.CommitOpen :: "Rand"]{dq} v.(CommitOpen.Rand')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (CommitOpen.Val' v)) (ktcore.CommitOpen) "Val"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.Memb *)
Module Memb.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  LabelProof' : slice.t;
  PkOpen' : loc;
  MerkleProof' : slice.t;
}.
End def.
End Memb.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.Memb.
#[local] Typeclasses Transparent ktcore.Memb.

Global Instance Memb_wf : struct.Wf ktcore.Memb.
Proof. apply _. Qed.

Global Instance settable_Memb : Settable Memb.t :=
  settable! Memb.mk < Memb.LabelProof'; Memb.PkOpen'; Memb.MerkleProof' >.
Global Instance into_val_Memb : IntoVal Memb.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.Memb [
    "LabelProof" ::= #(Memb.LabelProof' v);
    "PkOpen" ::= #(Memb.PkOpen' v);
    "MerkleProof" ::= #(Memb.MerkleProof' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_Memb : IntoValTyped Memb.t ktcore.Memb :=
{|
  default_val := Memb.mk (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_Memb_LabelProof : IntoValStructField "LabelProof" ktcore.Memb Memb.LabelProof'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_Memb_PkOpen : IntoValStructField "PkOpen" ktcore.Memb Memb.PkOpen'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_Memb_MerkleProof : IntoValStructField "MerkleProof" ktcore.Memb Memb.MerkleProof'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_Memb LabelProof' PkOpen' MerkleProof':
  PureWp True
    (struct.make #ktcore.Memb (alist_val [
      "LabelProof" ::= #LabelProof';
      "PkOpen" ::= #PkOpen';
      "MerkleProof" ::= #MerkleProof'
    ]))%struct
    #(Memb.mk LabelProof' PkOpen' MerkleProof').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance Memb_struct_fields_split dq l (v : Memb.t) :
  StructFieldsSplit dq l v (
    "HLabelProof" ∷ l ↦s[ktcore.Memb :: "LabelProof"]{dq} v.(Memb.LabelProof') ∗
    "HPkOpen" ∷ l ↦s[ktcore.Memb :: "PkOpen"]{dq} v.(Memb.PkOpen') ∗
    "HMerkleProof" ∷ l ↦s[ktcore.Memb :: "MerkleProof"]{dq} v.(Memb.MerkleProof')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (Memb.LabelProof' v)) (ktcore.Memb) "LabelProof"%go.
  simpl_one_flatten_struct (# (Memb.PkOpen' v)) (ktcore.Memb) "PkOpen"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.NonMemb *)
Module NonMemb.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  LabelProof' : slice.t;
  MerkleProof' : slice.t;
}.
End def.
End NonMemb.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.NonMemb.
#[local] Typeclasses Transparent ktcore.NonMemb.

Global Instance NonMemb_wf : struct.Wf ktcore.NonMemb.
Proof. apply _. Qed.

Global Instance settable_NonMemb : Settable NonMemb.t :=
  settable! NonMemb.mk < NonMemb.LabelProof'; NonMemb.MerkleProof' >.
Global Instance into_val_NonMemb : IntoVal NonMemb.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.NonMemb [
    "LabelProof" ::= #(NonMemb.LabelProof' v);
    "MerkleProof" ::= #(NonMemb.MerkleProof' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_NonMemb : IntoValTyped NonMemb.t ktcore.NonMemb :=
{|
  default_val := NonMemb.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_NonMemb_LabelProof : IntoValStructField "LabelProof" ktcore.NonMemb NonMemb.LabelProof'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_NonMemb_MerkleProof : IntoValStructField "MerkleProof" ktcore.NonMemb NonMemb.MerkleProof'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_NonMemb LabelProof' MerkleProof':
  PureWp True
    (struct.make #ktcore.NonMemb (alist_val [
      "LabelProof" ::= #LabelProof';
      "MerkleProof" ::= #MerkleProof'
    ]))%struct
    #(NonMemb.mk LabelProof' MerkleProof').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance NonMemb_struct_fields_split dq l (v : NonMemb.t) :
  StructFieldsSplit dq l v (
    "HLabelProof" ∷ l ↦s[ktcore.NonMemb :: "LabelProof"]{dq} v.(NonMemb.LabelProof') ∗
    "HMerkleProof" ∷ l ↦s[ktcore.NonMemb :: "MerkleProof"]{dq} v.(NonMemb.MerkleProof')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (NonMemb.LabelProof' v)) (ktcore.NonMemb) "LabelProof"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.AuditProof *)
Module AuditProof.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  Updates' : slice.t;
  LinkSig' : slice.t;
}.
End def.
End AuditProof.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.AuditProof.
#[local] Typeclasses Transparent ktcore.AuditProof.

Global Instance AuditProof_wf : struct.Wf ktcore.AuditProof.
Proof. apply _. Qed.

Global Instance settable_AuditProof : Settable AuditProof.t :=
  settable! AuditProof.mk < AuditProof.Updates'; AuditProof.LinkSig' >.
Global Instance into_val_AuditProof : IntoVal AuditProof.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.AuditProof [
    "Updates" ::= #(AuditProof.Updates' v);
    "LinkSig" ::= #(AuditProof.LinkSig' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_AuditProof : IntoValTyped AuditProof.t ktcore.AuditProof :=
{|
  default_val := AuditProof.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_AuditProof_Updates : IntoValStructField "Updates" ktcore.AuditProof AuditProof.Updates'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_AuditProof_LinkSig : IntoValStructField "LinkSig" ktcore.AuditProof AuditProof.LinkSig'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_AuditProof Updates' LinkSig':
  PureWp True
    (struct.make #ktcore.AuditProof (alist_val [
      "Updates" ::= #Updates';
      "LinkSig" ::= #LinkSig'
    ]))%struct
    #(AuditProof.mk Updates' LinkSig').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance AuditProof_struct_fields_split dq l (v : AuditProof.t) :
  StructFieldsSplit dq l v (
    "HUpdates" ∷ l ↦s[ktcore.AuditProof :: "Updates"]{dq} v.(AuditProof.Updates') ∗
    "HLinkSig" ∷ l ↦s[ktcore.AuditProof :: "LinkSig"]{dq} v.(AuditProof.LinkSig')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (AuditProof.Updates' v)) (ktcore.AuditProof) "Updates"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type ktcore.UpdateProof *)
Module UpdateProof.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  MapLabel' : slice.t;
  MapVal' : slice.t;
  NonMembProof' : slice.t;
}.
End def.
End UpdateProof.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent ktcore.UpdateProof.
#[local] Typeclasses Transparent ktcore.UpdateProof.

Global Instance UpdateProof_wf : struct.Wf ktcore.UpdateProof.
Proof. apply _. Qed.

Global Instance settable_UpdateProof : Settable UpdateProof.t :=
  settable! UpdateProof.mk < UpdateProof.MapLabel'; UpdateProof.MapVal'; UpdateProof.NonMembProof' >.
Global Instance into_val_UpdateProof : IntoVal UpdateProof.t :=
  {| to_val_def v :=
    struct.val_aux ktcore.UpdateProof [
    "MapLabel" ::= #(UpdateProof.MapLabel' v);
    "MapVal" ::= #(UpdateProof.MapVal' v);
    "NonMembProof" ::= #(UpdateProof.NonMembProof' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_UpdateProof : IntoValTyped UpdateProof.t ktcore.UpdateProof :=
{|
  default_val := UpdateProof.mk (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_UpdateProof_MapLabel : IntoValStructField "MapLabel" ktcore.UpdateProof UpdateProof.MapLabel'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_UpdateProof_MapVal : IntoValStructField "MapVal" ktcore.UpdateProof UpdateProof.MapVal'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_UpdateProof_NonMembProof : IntoValStructField "NonMembProof" ktcore.UpdateProof UpdateProof.NonMembProof'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_UpdateProof MapLabel' MapVal' NonMembProof':
  PureWp True
    (struct.make #ktcore.UpdateProof (alist_val [
      "MapLabel" ::= #MapLabel';
      "MapVal" ::= #MapVal';
      "NonMembProof" ::= #NonMembProof'
    ]))%struct
    #(UpdateProof.mk MapLabel' MapVal' NonMembProof').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance UpdateProof_struct_fields_split dq l (v : UpdateProof.t) :
  StructFieldsSplit dq l v (
    "HMapLabel" ∷ l ↦s[ktcore.UpdateProof :: "MapLabel"]{dq} v.(UpdateProof.MapLabel') ∗
    "HMapVal" ∷ l ↦s[ktcore.UpdateProof :: "MapVal"]{dq} v.(UpdateProof.MapVal') ∗
    "HNonMembProof" ∷ l ↦s[ktcore.UpdateProof :: "NonMembProof"]{dq} v.(UpdateProof.NonMembProof')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (UpdateProof.MapLabel' v)) (ktcore.UpdateProof) "MapLabel"%go.
  simpl_one_flatten_struct (# (UpdateProof.MapVal' v)) (ktcore.UpdateProof) "MapVal"%go.

  solve_field_ref_f.
Qed.

End instances.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_ktcore : IsPkgDefinedPure ktcore :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single ktcore ∧
      is_pkg_defined_pure code.bytes.bytes ∧
      is_pkg_defined_pure code.github_com.sanjit_bhat.pav.cryptoffi.cryptoffi ∧
      is_pkg_defined_pure code.github_com.sanjit_bhat.pav.cryptoutil.cryptoutil ∧
      is_pkg_defined_pure code.github_com.sanjit_bhat.pav.safemarshal.safemarshal ∧
      is_pkg_defined_pure code.github_com.tchajed.marshal.marshal;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_ktcore : IsPkgDefined ktcore :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single ktcore ∗
       is_pkg_defined code.bytes.bytes ∗
       is_pkg_defined code.github_com.sanjit_bhat.pav.cryptoffi.cryptoffi ∗
       is_pkg_defined code.github_com.sanjit_bhat.pav.cryptoutil.cryptoutil ∗
       is_pkg_defined code.github_com.sanjit_bhat.pav.safemarshal.safemarshal ∗
       is_pkg_defined code.github_com.tchajed.marshal.marshal)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_SignVrf :
  WpFuncCall ktcore.SignVrf _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_VerifyVrfSig :
  WpFuncCall ktcore.VerifyVrfSig _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_SignLink :
  WpFuncCall ktcore.SignLink _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_VerifyLinkSig :
  WpFuncCall ktcore.VerifyLinkSig _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_ProveMapLabel :
  WpFuncCall ktcore.ProveMapLabel _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_EvalMapLabel :
  WpFuncCall ktcore.EvalMapLabel _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_CheckMapLabel :
  WpFuncCall ktcore.CheckMapLabel _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_GetMapVal :
  WpFuncCall ktcore.GetMapVal _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_GetCommitRand :
  WpFuncCall ktcore.GetCommitRand _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_VrfSigEncode :
  WpFuncCall ktcore.VrfSigEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_VrfSigDecode :
  WpFuncCall ktcore.VrfSigDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_LinkSigEncode :
  WpFuncCall ktcore.LinkSigEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_LinkSigDecode :
  WpFuncCall ktcore.LinkSigDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MapLabelEncode :
  WpFuncCall ktcore.MapLabelEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MapLabelDecode :
  WpFuncCall ktcore.MapLabelDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_CommitOpenEncode :
  WpFuncCall ktcore.CommitOpenEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_CommitOpenDecode :
  WpFuncCall ktcore.CommitOpenDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MembEncode :
  WpFuncCall ktcore.MembEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MembDecode :
  WpFuncCall ktcore.MembDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_NonMembEncode :
  WpFuncCall ktcore.NonMembEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_NonMembDecode :
  WpFuncCall ktcore.NonMembDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_AuditProofEncode :
  WpFuncCall ktcore.AuditProofEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_AuditProofDecode :
  WpFuncCall ktcore.AuditProofDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_UpdateProofEncode :
  WpFuncCall ktcore.UpdateProofEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_UpdateProofDecode :
  WpFuncCall ktcore.UpdateProofDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_UpdateProofSlice1DEncode :
  WpFuncCall ktcore.UpdateProofSlice1DEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_UpdateProofSlice1DDecode :
  WpFuncCall ktcore.UpdateProofSlice1DDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MembSlice1DEncode :
  WpFuncCall ktcore.MembSlice1DEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_MembSlice1DDecode :
  WpFuncCall ktcore.MembSlice1DDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_AuditProofSlice1DEncode :
  WpFuncCall ktcore.AuditProofSlice1DEncode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_AuditProofSlice1DDecode :
  WpFuncCall ktcore.AuditProofSlice1DDecode _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_func_call).

Global Instance wp_method_call_Evid'ptr_Check :
  WpMethodCall (ptrT.id ktcore.Evid.id) "Check" _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_EvidVrf'ptr_check :
  WpMethodCall (ptrT.id ktcore.EvidVrf.id) "check" _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_EvidLink'ptr_check :
  WpMethodCall (ptrT.id ktcore.EvidLink.id) "check" _ (is_pkg_defined ktcore) :=
  ltac:(solve_wp_method_call).

End names.
End ktcore.
